print("The end", "or is it?", "keep watching to learn more about Python", 3)
print("Today is a good day to learn Python")
print('Python is fun')
print("Python's string are easy to use")
print('We can even include "quotes" in string')
print("hello" + " world")
greetings = "Hello"
name = input("Please Enter Your Name: ")
print(greetings + ' ' + name)
print(name)
